Repository process-engine/documentation, pull requests merged in 2018-06, with the labels that each got.

#93 restructure processengine.ts documentation
  SUMMARY.md
  processengine/ts/README.md
  processengine/ts/api/README.md
  processengine/ts/api/messagebus.md
  processengine/ts/architektur/README.md
  processengine/ts/architektur/adapters.md
  processengine/ts/architektur/bridges.md
  processengine/ts/architektur/contracts.md
  processengine/ts/architektur/dependendy-injection.md
  processengine/ts/architektur/discovery.md
  processengine/ts/architektur/extensions.md
  processengine/ts/architektur/images/adapters.png
  processengine/ts/architektur/images/bridges.png
  processengine/ts/architektur/images/contracts.png
  processengine/ts/architektur/images/dependency-graph.png
  processengine/ts/architektur/images/discovery.png
  processengine/ts/architektur/images/extensions.png
  processengine/ts/architektur/images/ioc-modules.png
  processengine/ts/architektur/structure.md
  processengine/ts/basics/README.md
  processengine/ts/basics/architektur/diagramm.md
  processengine/ts/basics/architektur/komponenten/README.md
  processengine/ts/basics/architektur/komponenten/abgrenzung.md
  processengine/ts/basics/erweiterte-architektur.md
  processengine/ts/cheat-sheet/messagebus/README.md
  processengine/ts/cheat-sheet/messagebus/external/README.md
  processengine/ts/konzepte/README.md
  processengine/ts/konzepte/configuration.md
  processengine/ts/konzepte/datastore.md
  processengine/ts/konzepte/entity-services.md
  processengine/ts/konzepte/identity-access-management.md
  processengine/ts/setup/README.md
  processengine/ts/setup/images/process-engine-and-bpmn-studio.png
  processengine/ts/setup/images/process-engine-standalone.png
  processengine/ts/setup/konfiguration.md
  processengine/ts/stack/README.md
  processengine/ts/stack/advanced-concepts/README.md
  processengine/ts/stack/basic-concepts/README.md
  processengine/ts/stack/module-interaction/README.md
Labels: documentation

#86 Consumer API User Manual
  GLOSSARY.md
  SUMMARY.md
  api/consumer-api.md
  api/consumer_api/README.md
  api/consumer_api/dealing_with_events.md
  api/consumer_api/images/consumer_api_architecture.png
  api/consumer_api/tasks/finish-user-task.md
  api/consumer_api/tasks/get-correlation-result.md
  api/consumer_api/tasks/list-startable-process-models.md
  api/consumer_api/tasks/list-triggerable-events.md
  api/consumer_api/tasks/list-waiting-usertasks.md
  api/consumer_api/tasks/receive-process-notifiations.md
  api/consumer_api/tasks/start-process-instance.md
  api/consumer_api/tasks/trigger-event.md
  api/consumer_api/technical-specifications.md
  bpmn-standard/styleguide.md
  getting-started/examples/hello-bpmn-world.md
  getting-started/examples/http-rest-api.md
  getting-started/examples/sending-emails.md
  processengine/ts/api/README.md
  processengine/ts/api/consumer_api/README.md
  processengine/ts/api/consumer_api/finish-user-task.md
  processengine/ts/api/consumer_api/get-correlation-result.md
  processengine/ts/api/consumer_api/images/consumer_api_architecture_external.png
  processengine/ts/api/consumer_api/images/consumer_api_architecture_internal.png
  processengine/ts/api/consumer_api/list-startable-process-models.md
  processengine/ts/api/consumer_api/list-waiting-usertasks.md
  processengine/ts/api/consumer_api/public_api.md
  processengine/ts/api/consumer_api/setup_external_process_engine.md
  processengine/ts/api/consumer_api/setup_internal_process_engine.md
  processengine/ts/api/consumer_api/start-process-instance.md
  processengine/ts/api/management_api/README.md
  processengine/ts/architektur/README.md
  processengine/ts/architektur/dependendy-injection.md
  processengine/ts/architektur/discovery.md
  processengine/ts/architektur/structure.md
  processengine/ts/konzepte/README.md
  processengine/ts/konzepte/configuration.md
Labels: discussion, documentation

#96 📚Add Introduction and Update Structure
  GLOSSARY.md
  README.md
  SUMMARY.md
  api/consumer_api/tasks/start-process-instance.md
  bpmn-standard/bpmn-basics/typisierte-tasks.md
  bpmn-standard/bpmn-process-engine/README.md
  bpmn-studio/beschreibung-ansichten.md
  getting-started/examples/README.md
  getting-started/examples/skateboard.md
  getting-started/installation.md
  images/bpmn-studio-icon.png
  images/process-engine-icon.png
  processengine/typescript/README.md
  processengine/typescript/api/README.md
  processengine/typescript/api/consumer_api/README.md
  processengine/typescript/api/consumer_api/finish-user-task.md
  processengine/typescript/api/consumer_api/get-correlation-result.md
  processengine/typescript/api/consumer_api/images/consumer_api_architecture_external.png
  processengine/typescript/api/consumer_api/images/consumer_api_architecture_internal.png
  processengine/typescript/api/consumer_api/list-startable-process-models.md
  processengine/typescript/api/consumer_api/list-waiting-usertasks.md
  processengine/typescript/api/consumer_api/public_api.md
  processengine/typescript/api/consumer_api/setup_external_process_engine.md
  processengine/typescript/api/consumer_api/setup_internal_process_engine.md
  processengine/typescript/api/consumer_api/start-process-instance.md
  processengine/typescript/api/management_api/README.md
  processengine/typescript/architektur/README.md
  processengine/typescript/architektur/adapters.md
  processengine/typescript/architektur/bridges.md
  processengine/typescript/architektur/contracts.md
  processengine/typescript/architektur/dependendy-injection.md
  processengine/typescript/architektur/discovery.md
  processengine/typescript/architektur/extensions.md
  processengine/typescript/architektur/images/adapters.png
  processengine/typescript/architektur/images/bridges.png
  processengine/typescript/architektur/images/contracts.png
  processengine/typescript/architektur/images/dependency-graph.png
  processengine/typescript/architektur/images/discovery.png
  processengine/typescript/architektur/images/extensions.png
  processengine/typescript/architektur/images/ioc-modules.png
  processengine/typescript/architektur/structure.md
  processengine/typescript/konzepte/README.md
  processengine/typescript/konzepte/configuration.md
  processengine/typescript/setup/README.md
  processengine/typescript/setup/images/process-engine-and-bpmn-studio.png
  processengine/typescript/setup/images/process-engine-standalone.png
  processengine/typescript/setup/konfiguration.md
Labels: documentation, enhancement
